name = "backend"
compatibility_date = "2023-12-01"

 [vars]
 DATABASE_URL = "prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMDk3ZGI1NTYtNGYyNy00MDFmLTlmNmYtNzQxNjU5YzI4MTY5IiwidGVuYW50X2lkIjoiNjNjZDM5NWUzMGEyODdiYTc1ODUzNDY3MDIzMTZjNDk1N2EwYTUwYWUyNmE1NTZjZWFkMWIyYTk1ODdkMGZhYiIsImludGVybmFsX3NlY3JldCI6IjZiMGE1Mjg0LWFmNmQtNGUzZC05ZjVkLTI0NjRiOGM2MDYxNiJ9.quF3_CfK-aq82-D3RcOHvoHM0y3MDPDSJLZMbrhh-zk"
